trigger:
- main

pool:
  name: jailbreak-pool

variables:
  TF_IN_AUTOMATION: "true"
  ARM_USE_AZURECLI: "true"

  RESOURCE_GROUP_NAME: cloudx-rg
  LOCATION: canadacentral
  KEY_VAULT_NAME: cloudx-keyvault3511
  KEY_VAULT_RESOURCE_GROUP: cloud-35-rg

stages:

- stage: Terraform_Plan
  displayName: Terraform Plan
  jobs:
  - job: Plan
    steps:
    - checkout: self

    - task: AzureCLI@2
      displayName: Azure Login
      inputs:
        azureSubscription: cloudx-azure-sc
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az account show

    - script: terraform init -input=false
      displayName: Terraform Init

    - script: |
        terraform plan \
          -input=false \
          -out=tfplan \
          -var "resource_group_name=$(RESOURCE_GROUP_NAME)" \
          -var "location=$(LOCATION)" \
          -var "key_vault_name=$(KEY_VAULT_NAME)" \
          -var "key_vault_resource_group_name=$(KEY_VAULT_RESOURCE_GROUP)"
      displayName: Terraform Plan

    - publish: tfplan
      artifact: terraform-plan

- stage: Terraform_Apply
  displayName: Terraform Apply
  dependsOn: Terraform_Plan
  condition: succeeded()

  jobs:
  - deployment: Apply
    environment: test
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          - download: current
            artifact: terraform-plan

          - script: |
              terraform init -input=false
              terraform apply -auto-approve tfplan
            displayName: Terraform Apply
