resource_group_name             = "cloudx-rg"
location                        = "canadacentral"
key_vault_resource_group_name   = "cloud-35-rg"
key_vault_name                  = "cloudx-keyvault3511"
allowed_rdp_ip                  = "0.0.0.0/0"
